apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-catalog
  description: Backstage service catalog
  annotations:
    github.com/project-slug: tomwakhungu/backstage-catalog
    backstage.io/kubernetes-id: backstage
    backstage.io/kubernetes-namespace: backstage
spec:
  type: service
  lifecycle: production
  owner: user:default/guest
