---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backstage-secrets
  namespace: backstage
spec:
  encryptedData:
    GITHUB_TOKEN: AgAC2xAqqhUj0HEMCfpNdRnDTymrzUiiuxCgrm2erDM6toOLWjn9N5NfvlL2g5EpddPgsEUWdaB27M/a///ehk1QY8kt8MCMNeF5M72GQujQASrbKUkohXxP55yHuaWCVp2JDZt2MWeEMmhqSKo5IYcZEIvi52pRMKENJLqCHoUHpMDnXaMR8KtAWAenx73ncJPcYIjt3jffgidJA+4envq8+jGwvG0N8GhW9SJ8JDQcqnA71vjnK8xJvkvoXcwPTBrpRaF0RXaDpyGIiONAMDcCMgMzYCEBsn+4VC/J0G1LazzK/n9R8K5eQcMrGDpMFI7UH+VuDWdmYGZ0x/kxqbbU9S4Ed/wueIJv9UwTmYQ6eDGIIGSXgT+USoDIGwV2j8uYwjglzb/4DBu3sPyneobjgIzmbeaEWeESLWrVqLd3rWWPdlZRJfCJ5OLxrFB0TJI25UXqhqfrzZdwsKvynW1F5JuR9mYGtU3f+yB5o6As6KsyUOScWC1hhIpiQwNRiqYCVMOwz95/ZNm/mLTzvjynuSwdMnw77P6Z/Ehp7NKp2vlwtQHzdExrw15pnRlocwTbwuGw8/vOqISAirbj9Te6b/ElZivJY9kRRgqxqgCWApT+j16Fu3W2CjiQTXSgghJx+kaMjKac+bwnQDXleQ1D8nj04bFc4ujAnk0N1u2prFYyWCcCKafGj+LmOPH3ZNcScwS8fwl0lF3b3PimImNocf9GsZJgpvF7RaPrzvOkxox4eLRjfLPq
  template:
    metadata:
      creationTimestamp: null
      name: backstage-secrets
      namespace: backstage
