---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: backstage
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCao90rWEo0v7HTUtjHdHO3UaIqTgOZPyC8VA0XFNi+StsiGuUj1XRqfiMJi1HKSCF23TIfuI0WKOdoqgk8Iw8UV5M2tlcJl7vt+o86/3TM/+XWwO/7N77dt6Rfff4EyNExkC3ZZO27IffqVD6//9hJRA/FfxXi1E8r+Lbp01UWuXj9Lh4OQ/q/DecdKhAJlzVj2XVaz2+JyTqCnShe5WJ4HiRTS6OCdZwAvoMT2EE/JXu2tAAjtu8nMGjW5FWUScd9Aec5uYRaE3ncOt0fF2Z99C0K0F7jg+92tDnOghzlifSLOxJnIa6SCaVXFXd4zBiG4+u/Tm9BvWwhRi2Gdi4MoV4PYeNzGU81lFCIXrtioktOe6L2jyMr5Ixt6o0jxdNCpLOB+65pn+3CqTSziJXpm45J80JYkJngkevRB5zly0WcOAThHajecE+9gEAlxpdR1Yfb/KID5U1TYf5IE1ktiqqyCL1IorzNvNSpGLZoRbP2wYKfALXo/LiB6NS+Q4ppwR5KEpuktkL4nRUSb2EOydsyjaiGw3kLtujgW+5XbxyIg0TZ73pOfQ9bQGYAtq9bz4UwmgYJgLTgVNtyiWcNsJ2tVTdsOmqsk1Au15g44mme1Qh9d4jua4iX3LNNvllVPjkDBxKtbPxwkDJde40Rrm0TvwuRG9bxD2ee9+lUfn7johbzeA9Q34Ruiih7uuKODCSjDIC6X7Ntgkf7gC25l/I=
    POSTGRES_USER: AgC4MP6MvurE2JvhhpKFE52SDXZjWETeGUi2KRllBApM62bkUEuKWgg9uUgIOOEhc4P82K1xHgCK42VOCKlPu7DDszNgNVi9n8+nVJstBMj/k7DMdeluubi6D+VWgYKHz0Sbr6FRDwLksrbNqBZxW6oaln99L6UT0ZfRLSe40ntrf6yRzrSAw78H8L+y8h9XWlB5wRYeO5ADr/SCE6SAK9/emCDKjASoGsXcD6ClG2DcvKuPthlmG5CoV5oJFTT/vPOCBIeKS3Q+0kQRTWX1aQaIK5gAjGUdad938BnyyBfBisW1bcV57AkYLASc6W9Y/DZQNvbyCw8lX/85f/XcZ8HrKRv9wZ9mXTelxmA3qyu10eHdUOBxImqXqx7Ww1lzbJPtNOef1asua6YrhE6cx7Fz6ATOBMScILXCtNicxIk5GP1Y/Slt3MGvomsuEQSduFuhezb2h/BsPBnwTg1DO5X6ibBdq09h4gR8umwstyd3hZ6BBuSjZfOUftwhRKBk5ey616zHdB+2YfZvoJNgiUmU7LO84GeT8A9G6016knkAH6CI5+uqtge4VRHJYkD9m05N78Hfv7r1ebsp1RP9wByb9PXbW8csNK0rl3abMocYhYLkSqt3RVNw5NG7wgPn1IqfMzHhYH9BQSeayHLFCEgRIB3ZQlHjxWlnbcj9NvXfQLYnQipnrke22CyCrF7+hHKUtpt0ObyA29g=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: backstage
